<?php

define('ADMIN', 'ADMIN');
define('CUSTOMER', 'CUSTOMER');
define('SELLER', 'SELLER');
define('PROFESSIONNAL', 'PROFESSIONAL');

define('USERTYPES', [
    ADMIN,
    CUSTOMER,
    SELLER,
    PROFESSIONNAL
]);

define('TRANSACTION_STATUS_SUCCESS', 'SUCCESS');
define('TRANSACTION_STATUS_FAILED', 'FAILED');

define('TRANSACTION_TYPE_ORDER', 'ORDER');
define('TRANSACTION_TYPE_SUBSCRIPTION', 'SUBSCRIPTION');
